<?php
session_start();

if (!file_exists(__DIR__ . '/config.php')) {
    header('Location: install.php');
    exit;
}

$config = require __DIR__ . '/config.php';
$pdo = new PDO($config['dsn'], $config['db_user'] ?? null, $config['db_pass'] ?? null, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
]);

function h($v) { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function auth_required() { if (empty($_SESSION['user'])) { header('Location: ?page=login'); exit; } }
function role_required(array $roles) { if (!in_array($_SESSION['user']['role'] ?? '', $roles, true)) { $_SESSION['flash'] = 'Permissão negada'; header('Location: ?page=dashboard'); exit; } }
function flash() { if (!empty($_SESSION['flash'])) { echo '<div class="alert">'.h($_SESSION['flash']).'</div>'; unset($_SESSION['flash']); } }
function simple_pdf($text, $filename='report.pdf') {
    $text = str_replace(["\r","\n"], ['',' '], $text);
    $stream = "BT /F1 12 Tf 50 750 Td (" . addcslashes($text, "()\\") . ") Tj ET";
    $pdf = "%PDF-1.4\n";
    $o1 = "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n";
    $o2 = "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n";
    $o3 = "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj\n";
    $o4 = "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n";
    $o5 = "5 0 obj << /Length ".strlen($stream)." >> stream\n$stream\nendstream endobj\n";
    $parts = [$o1,$o2,$o3,$o4,$o5];
    $offsets=[0];
    foreach($parts as $p){$offsets[] = strlen($pdf); $pdf .= $p;}
    $xref = strlen($pdf);
    $pdf .= "xref\n0 6\n0000000000 65535 f \n";
    for($i=1;$i<=5;$i++) $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
    $pdf .= "trailer << /Size 6 /Root 1 0 R >>\nstartxref\n$xref\n%%EOF";
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename='.$filename);
    echo $pdf; exit;
}

$page = $_GET['page'] ?? 'dashboard';

if ($page === 'logout') { session_destroy(); header('Location: ?page=login'); exit; }

if ($page === 'register' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $stmt = $pdo->prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)');
    $stmt->execute([$_POST['name'], strtolower(trim($_POST['email'])), password_hash($_POST['password'], PASSWORD_DEFAULT), $_POST['role']]);
    $_SESSION['flash'] = 'Conta criada! Faça login.';
    header('Location: ?page=login'); exit;
}
if ($page === 'login' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $stmt = $pdo->prepare('SELECT * FROM users WHERE email=?'); $stmt->execute([strtolower(trim($_POST['email']))]); $user = $stmt->fetch();
    if ($user && password_verify($_POST['password'], $user['password_hash'])) { $_SESSION['user'] = ['id'=>$user['id'], 'name'=>$user['name'], 'role'=>$user['role'], 'email'=>$user['email']]; header('Location: ?page=dashboard'); exit; }
    $_SESSION['flash'] = 'Credenciais inválidas'; header('Location: ?page=login'); exit;
}

if (in_array($page, ['login','register'], true)) {
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="static/style.css"><title>Pacaembu OS</title></head><body class="auth-body"><div class="auth-card"><h2><?= $page==='login'?'Login':'Registro' ?> - Pacaembu OS</h2><?php flash(); ?><form method="post" class="grid"><?php if($page==='register'): ?><input name="name" placeholder="Nome" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Senha" required><select name="role"><option>Admin</option><option>Designer</option><option>Social media manager</option><option>Copywriter</option><option>Developer</option><option>Client</option></select><button>Criar conta</button><?php else: ?><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Senha" required><button>Entrar</button><?php endif; ?></form><a href="?page=<?= $page==='login'?'register':'login' ?>"><?= $page==='login'?'Criar conta':'Já tenho conta' ?></a></div></body></html><?php exit; }

auth_required();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($page === 'clients_create') {
        $pdo->prepare('INSERT INTO clients(company_name,contact_name,whatsapp,email,website,instagram,facebook,tiktok,linkedin,service_plan,monthly_fee,status,internal_notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')
            ->execute([$_POST['company_name'],$_POST['contact_name'],$_POST['whatsapp'],$_POST['email'],$_POST['website'],$_POST['instagram'],$_POST['facebook'],$_POST['tiktok'],$_POST['linkedin'],$_POST['service_plan'],(float)$_POST['monthly_fee'],$_POST['status'],$_POST['internal_notes']]);
        $_SESSION['flash']='Cliente criado'; header('Location: ?page=clients'); exit;
    }
    if ($page === 'clients_delete') { role_required(['Admin']); $pdo->prepare('DELETE FROM clients WHERE id=?')->execute([$_POST['id']]); $_SESSION['flash']='Cliente removido'; header('Location: ?page=clients'); exit; }
    if ($page === 'projects_create') { $pdo->prepare('INSERT INTO projects(client_id,name,category,status,priority,deadline,responsible_user,comments,checklist) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$_POST['client_id'],$_POST['name'],$_POST['category'],$_POST['status'],$_POST['priority'],$_POST['deadline'],$_POST['responsible_user'],$_POST['comments'],$_POST['checklist']]); $_SESSION['flash']='Projeto salvo'; header('Location: ?page=projects'); exit; }
    if ($page === 'tasks_create') { $pdo->prepare('INSERT INTO tasks(client_id,project_id,title,description,status,priority,responsible_user,due_date,tags) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$_POST['client_id']?:null,$_POST['project_id']?:null,$_POST['title'],$_POST['description'],$_POST['status'],$_POST['priority'],$_POST['responsible_user'],$_POST['due_date'],$_POST['tags']]); $_SESSION['flash']='Tarefa criada'; header('Location: ?page=tasks&view='.urlencode($_GET['view'] ?? 'table')); exit; }
    if ($page === 'content_create') { $pdo->prepare('INSERT INTO content_calendar(client_id,platform,content_type,publish_date,caption,creative_briefing,references_link,approval_status,attached_file) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$_POST['client_id'],$_POST['platform'],$_POST['content_type'],$_POST['publish_date'],$_POST['caption'],$_POST['creative_briefing'],$_POST['references_link'],$_POST['approval_status'],$_POST['attached_file']]); $_SESSION['flash']='Conteúdo salvo'; header('Location: ?page=content'); exit; }
    if ($page === 'website_create') { $pdo->prepare('INSERT INTO website_projects(client_id,domain,hosting_provider,cms_platform,admin_url,project_stage,seo_checklist,performance_checklist,security_checklist,backup_status,maintenance_notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$_POST['client_id'],$_POST['domain'],$_POST['hosting_provider'],$_POST['cms_platform'],$_POST['admin_url'],$_POST['project_stage'],$_POST['seo_checklist'],$_POST['performance_checklist'],$_POST['security_checklist'],$_POST['backup_status'],$_POST['maintenance_notes']]); $_SESSION['flash']='Website salvo'; header('Location: ?page=website'); exit; }
    if ($page === 'metrics_create') { $pdo->prepare('INSERT INTO metrics(client_id,month,followers,reach,impressions,engagement,clicks,leads,conversions,website_traffic) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$_POST['client_id'],$_POST['month'],$_POST['followers'],$_POST['reach'],$_POST['impressions'],$_POST['engagement'],$_POST['clicks'],$_POST['leads'],$_POST['conversions'],$_POST['website_traffic']]); $_SESSION['flash']='Métricas salvas'; header('Location: ?page=metrics'); exit; }
    if ($page === 'finance_create') { $pdo->prepare('INSERT INTO payments(client_id,kind,amount,due_date,status,notes) VALUES(?,?,?,?,?,?)')->execute([$_POST['client_id'],$_POST['kind'],$_POST['amount'],$_POST['due_date'],$_POST['status'],$_POST['notes']]); $_SESSION['flash']='Pagamento salvo'; header('Location: ?page=finance'); exit; }
    if ($page === 'approvals_create') { $pdo->prepare('INSERT INTO approvals(client_id,item_type,item_id,status,notes) VALUES(?,?,?,?,?)')->execute([$_POST['client_id'],$_POST['item_type'],$_POST['item_id'],$_POST['status'],$_POST['notes']]); $_SESSION['flash']='Aprovação registrada'; header('Location: ?page=approvals'); exit; }
    if ($page === 'reports_create') { $stmt=$pdo->prepare('SELECT COUNT(*) c FROM tasks WHERE client_id=? AND status="done"'); $stmt->execute([$_POST['client_id']]); $done=$stmt->fetch()['c']; $stmt=$pdo->prepare('SELECT COUNT(*) c FROM content_calendar WHERE client_id=? AND approval_status="published"'); $stmt->execute([$_POST['client_id']]); $pub=$stmt->fetch()['c']; $summary="Concluídas: $done; Publicadas: $pub; Recomenda-se aumentar conteúdos com CTA."; $pdo->prepare('INSERT INTO reports(client_id,month,summary) VALUES(?,?,?)')->execute([$_POST['client_id'],$_POST['month'],$summary]); $_SESSION['flash']='Relatório gerado'; header('Location: ?page=reports'); exit; }
    if ($page === 'assistant_ask') { $over = $pdo->query("SELECT COUNT(*) c FROM tasks WHERE status!='done' AND due_date < date('now')")->fetch()['c']; $ans = "Foque em $over tarefas atrasadas, validar aprovações pendentes e revisar clientes com baixa conversão."; $pdo->prepare('INSERT INTO ai_logs(user_id,prompt,response) VALUES(?,?,?)')->execute([$_SESSION['user']['id'],$_POST['prompt'],$ans]); $_SESSION['flash']=$ans; header('Location: ?page=assistant'); exit; }
    if ($page === 'files_upload') {
        $filename=''; $path='';
        if (!empty($_FILES['file']['name'])) { $filename = basename($_FILES['file']['name']); $path = 'uploads/'.time().'_'.$filename; move_uploaded_file($_FILES['file']['tmp_name'], __DIR__.'/'.$path); }
        $pdo->prepare('INSERT INTO files(client_id,project_id,filename,filepath,notes) VALUES(?,?,?,?,?)')->execute([$_POST['client_id']?:null,$_POST['project_id']?:null,$filename,$path,$_POST['notes']]);
        $_SESSION['flash']='Arquivo enviado'; header('Location: ?page=files'); exit;
    }
}

if ($page === 'report_pdf') { $id=(int)($_GET['id']??0); $r=$pdo->prepare('SELECT r.*, c.company_name FROM reports r JOIN clients c ON c.id=r.client_id WHERE r.id=?'); $r->execute([$id]); $row=$r->fetch(); if($row){ simple_pdf("Pacaembu OS - {$row['company_name']} {$row['month']} {$row['summary']}", "report-$id.pdf"); } }

$q = trim($_GET['q'] ?? '');
$clients = $pdo->query('SELECT * FROM clients ORDER BY id DESC')->fetchAll();
$projects = $pdo->query('SELECT p.*, c.company_name FROM projects p LEFT JOIN clients c ON c.id=p.client_id ORDER BY p.id DESC')->fetchAll();
$tasks = $pdo->query('SELECT t.*, c.company_name, p.name project_name FROM tasks t LEFT JOIN clients c ON c.id=t.client_id LEFT JOIN projects p ON p.id=t.project_id ORDER BY t.id DESC')->fetchAll();
$content = $pdo->query('SELECT cc.*, c.company_name FROM content_calendar cc LEFT JOIN clients c ON c.id=cc.client_id ORDER BY publish_date DESC')->fetchAll();
$websites = $pdo->query('SELECT wp.*, c.company_name FROM website_projects wp LEFT JOIN clients c ON c.id=wp.client_id ORDER BY wp.id DESC')->fetchAll();
$metrics = $pdo->query('SELECT m.*, c.company_name FROM metrics m LEFT JOIN clients c ON c.id=m.client_id ORDER BY m.id DESC')->fetchAll();
$payments = $pdo->query('SELECT pay.*, c.company_name FROM payments pay LEFT JOIN clients c ON c.id=pay.client_id ORDER BY pay.id DESC')->fetchAll();
$approvals = $pdo->query('SELECT a.*, c.company_name FROM approvals a LEFT JOIN clients c ON c.id=a.client_id ORDER BY a.id DESC')->fetchAll();
$reports = $pdo->query('SELECT r.*, c.company_name FROM reports r LEFT JOIN clients c ON c.id=r.client_id ORDER BY r.id DESC')->fetchAll();
$files = $pdo->query('SELECT f.*, c.company_name, p.name project_name FROM files f LEFT JOIN clients c ON c.id=f.client_id LEFT JOIN projects p ON p.id=f.project_id ORDER BY f.id DESC')->fetchAll();
$ai_logs = $pdo->query('SELECT * FROM ai_logs ORDER BY id DESC LIMIT 10')->fetchAll();

$activeClients = $pdo->query("SELECT COUNT(*) c FROM clients WHERE status='active'")->fetch()['c'];
$activeProjects = $pdo->query("SELECT COUNT(*) c FROM projects WHERE status IN ('planning','in progress','waiting approval','revision')")->fetch()['c'];
$todayTasks = $pdo->query("SELECT COUNT(*) c FROM tasks WHERE due_date=date('now')")->fetch()['c'];
$overdueTasks = $pdo->query("SELECT COUNT(*) c FROM tasks WHERE due_date<date('now') AND status!='done'")->fetch()['c'];
$revenueEstimate = $pdo->query("SELECT COALESCE(SUM(amount),0) c FROM payments WHERE status!='overdue'")->fetch()['c'];

?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pacaembu OS</title><link rel="stylesheet" href="static/style.css"></head><body>
<div class="app-shell"><aside class="sidebar"><h3>Pacaembu OS</h3><a href="?page=dashboard">Dashboard</a><a href="?page=clients">Clientes</a><a href="?page=projects">Projetos</a><a href="?page=tasks">Tarefas</a><a href="?page=content">Editorial</a><a href="?page=website">Websites</a><a href="?page=metrics">Métricas</a><a href="?page=reports">Relatórios</a><a href="?page=finance">Financeiro</a><a href="?page=files">Arquivos</a><a href="?page=approvals">Aprovações</a><a href="?page=assistant">IA</a><a href="?page=logout">Sair</a></aside>
<main class="content-area"><header class="topbar"><form><input name="q" placeholder="Busca global" value="<?=h($q)?>"><input type="hidden" name="page" value="search"><button>Buscar</button></form><div><?=h($_SESSION['user']['name'])?> (<?=h($_SESSION['user']['role'])?>)</div></header><?php flash();
if ($page==='dashboard') { echo "<div class='tile-grid'><div class='tile'><h4>Clientes ativos</h4><p>$activeClients</p></div><div class='tile'><h4>Projetos ativos</h4><p>$activeProjects</p></div><div class='tile'><h4>Hoje</h4><p>$todayTasks</p></div><div class='tile'><h4>Atrasadas</h4><p>$overdueTasks</p></div><div class='tile'><h4>Receita estimada</h4><p>R$ ".number_format((float)$revenueEstimate,2,',','.')."</p></div></div><div class='panel'><h4>Sugestões IA do dia</h4><ul><li>Priorize tarefas vencidas até 12h.</li><li>Finalize conteúdos aguardando aprovação.</li><li>Cobrança ativa para pagamentos pendentes.</li></ul></div>"; }
if ($page==='clients') { ?><h2>Clientes</h2><form method="post" action="?page=clients_create" class="panel grid2"><input name="company_name" placeholder="Empresa" required><input name="contact_name" placeholder="Contato"><input name="whatsapp" placeholder="WhatsApp"><input name="email" placeholder="Email"><input name="website" placeholder="Site"><input name="instagram" placeholder="Instagram"><input name="facebook" placeholder="Facebook"><input name="tiktok" placeholder="TikTok"><input name="linkedin" placeholder="LinkedIn"><input name="service_plan" placeholder="Plano"><input name="monthly_fee" type="number" step="0.01" placeholder="Mensalidade"><select name="status"><option>active</option><option>paused</option><option>cancelled</option><option>prospect</option></select><textarea name="internal_notes" placeholder="Notas"></textarea><button>Salvar cliente</button></form><div class="panel table-wrap"><table><tr><th>Empresa</th><th>Status</th><th>Plano</th><th>Valor</th><th>Ação</th></tr><?php foreach($clients as $c){ ?><tr><td><?=h($c['company_name'])?></td><td><?=h($c['status'])?></td><td><?=h($c['service_plan'])?></td><td><?=h($c['monthly_fee'])?></td><td><form method="post" action="?page=clients_delete" onsubmit="return confirm('Excluir?')"><input type="hidden" name="id" value="<?=$c['id']?>"><button>Excluir</button></form></td></tr><?php } ?></table></div><?php }
if ($page==='projects') { ?><h2>Projetos</h2><form method="post" action="?page=projects_create" class="panel grid2"><select name="client_id"><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><input name="name" placeholder="Nome" required><select name="category"><option>social media</option><option>website</option><option>landing page</option><option>branding</option><option>paid traffic</option><option>maintenance</option><option>consulting</option></select><select name="status"><option>planning</option><option>in progress</option><option>waiting approval</option><option>revision</option><option>completed</option><option>cancelled</option></select><select name="priority"><option>low</option><option>medium</option><option>high</option></select><input type="date" name="deadline"><input name="responsible_user" placeholder="Responsável"><input name="checklist" placeholder="Checklist"><textarea name="comments" placeholder="Comentários"></textarea><button>Salvar projeto</button></form><div class="panel table-wrap"><table><tr><th>Projeto</th><th>Cliente</th><th>Status</th><th>Prazo</th></tr><?php foreach($projects as $p) echo '<tr><td>'.h($p['name']).'</td><td>'.h($p['company_name']).'</td><td>'.h($p['status']).'</td><td>'.h($p['deadline']).'</td></tr>'; ?></table></div><?php }
if ($page==='tasks') { $view=$_GET['view']??'table'; ?><h2>Tarefas</h2><p><a href="?page=tasks&view=table">Tabela</a> | <a href="?page=tasks&view=kanban">Kanban</a> | <a href="?page=tasks&view=calendar">Calendário</a> | <a href="?page=tasks&view=timeline">Timeline</a></p><form method="post" action="?page=tasks_create&view=<?=h($view)?>" class="panel grid2"><input name="title" placeholder="Título" required><textarea name="description" placeholder="Descrição"></textarea><select name="status"><option>todo</option><option>doing</option><option>done</option><option>blocked</option></select><select name="priority"><option>low</option><option>medium</option><option>high</option></select><input name="responsible_user" placeholder="Responsável"><input type="date" name="due_date"><input name="tags" placeholder="Tags"><select name="client_id"><option value="">Sem cliente</option><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><select name="project_id"><option value="">Sem projeto</option><?php foreach($projects as $p) echo '<option value="'.$p['id'].'">'.h($p['name']).'</option>'; ?></select><button>Adicionar tarefa</button></form><?php if($view==='kanban'){ ?><div class="kanban"><?php foreach(['todo','doing','done','blocked'] as $st){ echo '<div class="panel"><h4>'.$st.'</h4>'; foreach($tasks as $t){ if($t['status']===$st) echo '<div class="task-chip">'.h($t['title']).'</div>'; } echo '</div>'; } ?></div><?php } else { ?><div class="panel table-wrap"><table><tr><th>Título</th><th>Status</th><th>Prioridade</th><th>Vencimento</th></tr><?php foreach($tasks as $t) echo '<tr><td>'.h($t['title']).'</td><td>'.h($t['status']).'</td><td>'.h($t['priority']).'</td><td>'.h($t['due_date']).'</td></tr>'; ?></table></div><?php }}
if ($page==='content') { ?><h2>Calendário Editorial</h2><form method="post" action="?page=content_create" class="panel grid2"><select name="client_id"><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><input name="platform" placeholder="Plataforma" required><input name="content_type" placeholder="Tipo" required><input type="date" name="publish_date" required><textarea name="caption" placeholder="Legenda"></textarea><input name="creative_briefing" placeholder="Briefing criativo"><input name="references_link" placeholder="Referências"><select name="approval_status"><option>draft</option><option>internal review</option><option>sent to client</option><option>approved</option><option>changes requested</option><option>published</option></select><input name="attached_file" placeholder="Arquivo/Link"><button>Salvar conteúdo</button></form><div class="panel table-wrap"><table><tr><th>Data</th><th>Cliente</th><th>Plataforma</th><th>Status</th></tr><?php foreach($content as $i) echo '<tr><td>'.h($i['publish_date']).'</td><td>'.h($i['company_name']).'</td><td>'.h($i['platform']).'</td><td>'.h($i['approval_status']).'</td></tr>'; ?></table></div><?php }
if ($page==='website') { ?><h2>Website Projects</h2><form method="post" action="?page=website_create" class="panel grid2"><select name="client_id"><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><input name="domain" placeholder="Domínio"><input name="hosting_provider" placeholder="Hospedagem"><input name="cms_platform" placeholder="CMS"><input name="admin_url" placeholder="Admin URL"><input name="project_stage" placeholder="Etapa"><input name="seo_checklist" placeholder="SEO checklist"><input name="performance_checklist" placeholder="Performance checklist"><input name="security_checklist" placeholder="Security checklist"><input name="backup_status" placeholder="Backup"><textarea name="maintenance_notes" placeholder="Notas"></textarea><button>Salvar</button></form><div class="panel table-wrap"><table><tr><th>Cliente</th><th>Domínio</th><th>Etapa</th></tr><?php foreach($websites as $w) echo '<tr><td>'.h($w['company_name']).'</td><td>'.h($w['domain']).'</td><td>'.h($w['project_stage']).'</td></tr>'; ?></table></div><?php }
if ($page==='metrics') { ?><h2>Métricas</h2><form method="post" action="?page=metrics_create" class="panel grid2"><select name="client_id"><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><input type="month" name="month" required><input type="number" name="followers" placeholder="Followers"><input type="number" name="reach" placeholder="Reach"><input type="number" name="impressions" placeholder="Impressions"><input type="number" name="engagement" placeholder="Engagement"><input type="number" name="clicks" placeholder="Clicks"><input type="number" name="leads" placeholder="Leads"><input type="number" name="conversions" placeholder="Conversions"><input type="number" name="website_traffic" placeholder="Website Traffic"><button>Salvar métricas</button></form><div class="panel"><strong>Insight IA:</strong> Se o alcance subir sem conversão, ajuste CTA e página de destino.</div><div class="panel table-wrap"><table><tr><th>Mês</th><th>Cliente</th><th>Followers</th><th>Reach</th><th>Conversions</th></tr><?php foreach($metrics as $m) echo '<tr><td>'.h($m['month']).'</td><td>'.h($m['company_name']).'</td><td>'.h($m['followers']).'</td><td>'.h($m['reach']).'</td><td>'.h($m['conversions']).'</td></tr>'; ?></table></div><?php }
if ($page==='reports') { ?><h2>Relatórios</h2><form method="post" action="?page=reports_create" class="panel grid2"><select name="client_id"><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><input type="month" name="month" required><button>Gerar relatório</button></form><div class="panel table-wrap"><table><tr><th>Cliente</th><th>Mês</th><th>Resumo</th><th>Exportar</th></tr><?php foreach($reports as $r) echo '<tr><td>'.h($r['company_name']).'</td><td>'.h($r['month']).'</td><td>'.h($r['summary']).'</td><td><a href="?page=report_pdf&id='.$r['id'].'">PDF</a></td></tr>'; ?></table></div><?php }
if ($page==='finance') { ?><h2>Financeiro</h2><form method="post" action="?page=finance_create" class="panel grid2"><select name="client_id"><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><select name="kind"><option>retainer</option><option>one-time</option></select><input name="amount" type="number" step="0.01" placeholder="Valor"><input type="date" name="due_date"><select name="status"><option>paid</option><option>pending</option><option>overdue</option></select><textarea name="notes" placeholder="Notas"></textarea><button>Salvar</button></form><div class="panel table-wrap"><table><tr><th>Cliente</th><th>Tipo</th><th>Valor</th><th>Status</th></tr><?php foreach($payments as $p) echo '<tr><td>'.h($p['company_name']).'</td><td>'.h($p['kind']).'</td><td>'.h($p['amount']).'</td><td>'.h($p['status']).'</td></tr>'; ?></table></div><?php }
if ($page==='files') { ?><h2>Arquivos</h2><form method="post" action="?page=files_upload" enctype="multipart/form-data" class="panel grid2"><input type="file" name="file" required><select name="client_id"><option value="">Sem cliente</option><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><select name="project_id"><option value="">Sem projeto</option><?php foreach($projects as $p) echo '<option value="'.$p['id'].'">'.h($p['name']).'</option>'; ?></select><input name="notes" placeholder="Notas"><button>Enviar arquivo</button></form><div class="panel table-wrap"><table><tr><th>Arquivo</th><th>Cliente</th><th>Projeto</th><th>Link</th></tr><?php foreach($files as $f) echo '<tr><td>'.h($f['filename']).'</td><td>'.h($f['company_name']).'</td><td>'.h($f['project_name']).'</td><td><a target="_blank" href="'.h($f['filepath']).'">Abrir</a></td></tr>'; ?></table></div><?php }
if ($page==='approvals') { ?><h2>Aprovações</h2><form method="post" action="?page=approvals_create" class="panel grid2"><select name="client_id"><?php foreach($clients as $c) echo '<option value="'.$c['id'].'">'.h($c['company_name']).'</option>'; ?></select><input name="item_type" placeholder="Tipo item"><input name="item_id" type="number" placeholder="Item ID"><select name="status"><option>draft</option><option>internal review</option><option>sent to client</option><option>approved</option><option>changes requested</option><option>published</option></select><textarea name="notes" placeholder="Notas"></textarea><button>Registrar</button></form><div class="panel table-wrap"><table><tr><th>Cliente</th><th>Item</th><th>Status</th></tr><?php foreach($approvals as $a) echo '<tr><td>'.h($a['company_name']).'</td><td>'.h($a['item_type']).' #'.h($a['item_id']).'</td><td>'.h($a['status']).'</td></tr>'; ?></table></div><?php }
if ($page==='assistant') { ?><h2>Assistente IA</h2><form method="post" action="?page=assistant_ask" class="panel"><textarea name="prompt" placeholder="No que devo focar hoje?" required></textarea><button>Analisar</button></form><div class="panel"><h4>Histórico</h4><ul><?php foreach($ai_logs as $l) echo '<li><b>'.h($l['prompt']).'</b><br>'.h($l['response']).'</li>'; ?></ul></div><?php }
if ($page==='search') {
    $s1=$pdo->prepare('SELECT company_name AS label, "Cliente" AS type FROM clients WHERE company_name LIKE ?');$s1->execute(["%$q%"]);
    $s2=$pdo->prepare('SELECT name AS label, "Projeto" AS type FROM projects WHERE name LIKE ?');$s2->execute(["%$q%"]);
    $s3=$pdo->prepare('SELECT title AS label, "Tarefa" AS type FROM tasks WHERE title LIKE ?');$s3->execute(["%$q%"]);
    $res=array_merge($s1->fetchAll(),$s2->fetchAll(),$s3->fetchAll());
    echo '<h2>Busca Global: '.h($q).'</h2><div class="panel table-wrap"><table><tr><th>Tipo</th><th>Resultado</th></tr>'; foreach($res as $r) echo '<tr><td>'.h($r['type']).'</td><td>'.h($r['label']).'</td></tr>'; echo '</table></div>';
}
?></main></div></body></html>
